### ISSUE TITLE
Как установить при отправке указать код ПВЗ получателя?

### ISSUE THREAD

**Issue by motoroller1983** [AntistressStore/cdek-sdk-v2#13]
$order = (new \AntistressStore\CdekSDK2\Entity\Requests\Order())
            ->setNumber('НовыйЗаказ1') // Номер заказа
            ->setType(1)                      // Тип заказа (ИМ)
            ->setComment('Оплата по карте') // Комментарий
            ->setTariffCode(136) // Код тарифа
            ->setDeliveryRecipientCost(150,55) // Стоимость доставки
            ->setPrint('waybill') // Запрос создать файл накладной вместе с заказом

в описании к API есть delivery_point

**Comment by AntistressStore** [comment]
"установить при отправке указать"??? 

$order->**setShipmentPoint**('Перед тем как плодить комментарии сразу в двух ветках, постарайтесь сами внимательно разобраться. Полезное качество для программиста')
 ->**setDeliveryPoint**('перед тем как задавать вопрос, ознакомьтесь с документацией СДЭК АПИ 2.0');

**Comment by motoroller1983** [comment]
Спасибо, может вопрос не к вам, но всё же формирую заказ успешно, появляется в ЛК cl'r/
Но когда вывожу данные по заказу cdek_number NULL 
ну и метод getCdekNumber аналогично возвращает, не подскажите с чем может быть связано? Естесвенно в ЛК номер сформирован.

**Comment by motoroller1983** [comment]
object(GuzzleHttp\Psr7\Stream)#240 (7) {
  ["stream":"GuzzleHttp\Psr7\Stream":private]=>
  resource(142) of type (stream)
  ["size":"GuzzleHttp\Psr7\Stream":private]=>
  NULL
  ["seekable":"GuzzleHttp\Psr7\Stream":private]=>
  bool(true)
  ["readable":"GuzzleHttp\Psr7\Stream":private]=>
  bool(true)
  ["writable":"GuzzleHttp\Psr7\Stream":private]=>
  bool(true)
  ["uri":"GuzzleHttp\Psr7\Stream":private]=>
  string(10) "php://temp"
  ["customMetadata":"GuzzleHttp\Psr7\Stream":private]=>
  array(0) {
  }
}

Как я понимаю, я получаю пустые данные по формированию PDF документа, 
собственно перед выполнением постаитл sleep 10, не помогло
