### ISSUE TITLE
некорректное объявление методов setServices() и setPackages()

### ISSUE THREAD

**Issue by filinme** [AntistressStore/cdek-sdk-v2#18]
В методе регистрации заказа некорректно указан тип входного параметра в объявлении методов setServices() и setPackages().

Возникающие ошибки:
1 passed to AntistressStore\\CdekSDK2\\Entity\\Requests\\Order::setServices() must be an instance of AntistressStore\\CdekSDK2\\Entity\\Requests\\Services, array given
1 passed to AntistressStore\\CdekSDK2\\Entity\\Requests\\Order::setPackages() must be an instance of AntistressStore\\CdekSDK2\\Entity\\Requests\\Package, array given

Корректное объявление методов:
public function setServices(array $services)
public function setPackages(array $packages)
+
ошибка при присваивании, корректно:
$this->packages = $packages;

**Comment by AntistressStore** [comment]
Исправлено в версии 1.2.3, функции принимают mixed для обратной совместимости
```
AntistressStore\CdekSDK2\Entity\Requests\Order::setServices()
public function setServices(mixed $services) 
AntistressStore\CdekSDK2\Entity\Requests\Order::setPackages() 
setPackages(mixed $packages)
```
Можно передавать как раньше экземпляр класса Package или Services в этом случае добавитcя единичная упаковка или сервис, можно передавать целым массивов, тогда массив элементов добавиться к существующим.
Важно помнить, что массив должен содержать подготовленные классы Package или Services, пример для $packages:
```
        $packages =
        (new \AntistressStore\CdekSDK2\Entity\Requests\Package())
            ->setNumber('1')
            ->setWeight(500)
            ->setHeight(10)
            ->setWidth(10)
            ->setLength(10)
        ;
```
Для добавления сервисов есть более удобная экспресс функция `->addServices(['INSURANCE' => 1000])` в которую передается массив ключ - значение, а функция сама подготовит правильный класс.
