### ISSUE TITLE
Перестала работать ваша библиотека

### ISSUE THREAD

**Issue by RustHrust** [AntistressStore/cdek-sdk-v2#21]
Здравствуйте! Сайт: shop-site.su надо положить товар в корзину и попробовать перейти на страницу оформления заказа, там должна быть карта пунктов СДЭК по Москве, но теперь выдает ошибку. С чем это связано? Спасибо!

**Comment by RustHrust** [comment]
Код ошибки: Исключение

Текст ошибки: cURL error 28: Operation timed out after 5001 milliseconds with 0 out of -1 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.edu.cdek.ru/v2/oauth/token?parameters

Файл, в котором произошла ошибка: /home/srv46830/shop-site.su/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php

Строка, в которой произошла ошибка: 210

**Comment by RustHrust** [comment]
Теперь другая ошибка:

Код ошибки: Исключение

Текст ошибки: От API CDEK при вызове метода deliverypoints пришел пустой ответ

Файл, в котором произошла ошибка: /home/srv46830/shop-site.su/vendor/antistress-store/cdek-sdk-v2/src/CdekClientV2.php

Строка, в которой произошла ошибка: 309

**Comment by AntistressStore** [comment]
Здравствуйте, это не проблема SDK. Это проблема настроек запроса, либо временные проблемы сервера СДЭК.
Проверял вчера и только что сегодня, все работает без проблем
![Screenshot_20230109_162045](https://user-images.githubusercontent.com/80528523/211317682-8025962f-bc79-4db8-86f2-f4573e35a241.png)

**Comment by RustHrust** [comment]
Все работало до нового года примерно, потом решил зайти проверить и на тебе...
Мой запрос выглядит вот так:

`<?php

namespace app\models;
use AntistressStore\CdekSDK2\Entity\Requests\DeliveryPoints;
use AntistressStore\CdekSDK2\CdekClientV2;
use AntistressStore\CdekSDK2\Entity\Requests\Tariff;

class Delivery extends AppModel {

    protected $client = '';
    protected $secure = '';
    public $params_pvz = [];
    public $params_tariff = [];

    // Авторизация магазина в СДЕК
    public function getAuth() {
        $client = new CdekClientV2('TEST');
        return $client;
    }
    // Список пунктов вывоза (ПВЗ) СДЕК
    public function getOffice() {
        $client = $this->getAuth();
        $requestPvz = (new DeliveryPoints())->setCountryCode('RU')->setRegionCode(81)->setCityCode(44)->setType('ALL');
        $responsePvz = $client->getDeliveryPoints($requestPvz);

        foreach ($responsePvz as $item) {
            $this->params_pvz[] = [
                'points' => $item->getLocation()->getLatitude().','.$item->getLocation()->getLongitude(),
                'code' => $item->getCode(),
                'address' => $item->getLocation()->getAddress(),
                'metro' => $item->getNearestMetroStation(),
                'work_time' => $item->getWorkTime(),
                'phones' => $item->getPhones(),
                'type' => $item->getType(),
                'weight_min' => $item->getWeightMin(),
                'weight_max' => $item->getWeightMax()
            ];
//            $item->getCode();
//            $item->getName();
//            $item->getLocation()->getAddress();
//            $item->getWorkTime();
//            $item->getLocation()->getLatitude();
//            $item->getWorkTimeList();
//            $item->getWorkTimeExceptions();
//            $item->getNote();
//            $item->getOwnerCode();
//            $item->getNearestStation();
//            $item->getNearestMetroStation();
//            $item->getSite();
//            $item->getEmail();
//            $item->getAddressComment();
//            $item->getOfficeImageList();
//            $item->getDimensions();
//            $item->getHaveCashless();
//            $item->getHaveCash();
//            $item->getAllowedCod();
//            $item->getIsDressingRoom();
//            $item->getIsHandout();
//            $item->getIsReception();
//            $item->getWeightMax();
//            $item->getWeightMin();
//            $item->getTakeOnly();
        }
        return $this->params_pvz;
    }

    public function getWeight() {
        $weight = 0;
        if(!empty($_SESSION['cart'])) {
            foreach ($_SESSION['cart'] as $id => $item) {
                $weight += $item['weight'] * $item['qty'];
            }
            return $weight;
        }
    }

    public function getTariff() {
        $client = $this->getAuth();
        $weight = $this->getWeight();
        if($weight != '') {
            $tariff = (new Tariff())
                ->setCityCodes(44, 44)// Экспресс-метод установки кодов отправителя и получателя
                ->setPackageWeight($this->getWeight())
                ->addServices(['CARTON_BOX_XS']);
        }else{
            $tariff = (new Tariff())
                ->setCityCodes(44, 44)// Экспресс-метод установки кодов отправителя и получателя
                ->setPackageWeight(100)
                ->addServices(['CARTON_BOX_XS']);
        }
        $tariffList = $client->calculateTariffList($tariff);
        foreach ($tariffList as $result) {
            $this->params_tariff[] = [
                'tariff_name' => $result->getTariffName(),
                'tariff_code' => $result->getTariffCode(),
                'delivery_sum' => $result->getDeliverySum(),
                'period_min' => $result->getPeriodMin(),
                'period_max' => $result->getPeriodMax()
            ];
//            $result->getTariffName(); // Код тарифа
//            $result->getTariffCode(); // Название тарифа
//            $result->getTariffDescription(); // Описание тарифа
//            $result->getDeliverySum(); // Стоимость доставки
//            $result->getDeliveryMode(); // Режим тарифа
//            $result->getPeriodMin(); // Минимальное время доставки (в рабочих днях)
//            $result->getPeriodMax(); // Максимальное время доставки (в рабочих днях)
        }
        return $this->params_tariff;
    }

}`
Проблема до сих пор имеет место быть, может подскажете почему? Я пробовал другую библиотеку, но в ней не было калькулятора расчета доставки, что странно, потому что ее позиционируют как официальную.
