### ISSUE TITLE
Возможность изменять timeout для GuzzleClient

### ISSUE THREAD

**Issue by vaiil** [AntistressStore/cdek-sdk-v2#8]
На некоторых запросах падает c ошибкой по timeout-у. Например, при получении списка ПВЗ (падает через раз). Хотелось бы иметь возможность задавать timeout  или передавать GuzzleClient самостоятельно.

**Comment by AntistressStore** [comment]
Здравствуйте. Не могу сказать, что это проблема sdk. Регулярно пользуюсь и калькулятором, и созданием\редактирование заказа с проблемой таймаута не встречался. В планы поставил вашу просьбу " задавать timeout или передавать GuzzleClient самостоятельно"

**Comment by motoroller1983** [comment]
Проблема с time Out реально есть!

**Comment by AntistressStore** [comment]
Еще раз обращаю внимание, это "реально" не проблема, а желаемое дополнение. Большая разница. Дополнение в работе.
